training:
  batch_size: 32 # rtx 24GB: <= 64
  n_epochs: 1600
  train_verbose_freq: 2000
  evaluate_freq: 5000
  snapshot_freq: 5000
  distributed: true
  world_size: 8
  local_rank: -1
  dist_on_itp: false
  dist_url: "env://"
  gpu: -1

test:
  begin_ckpt: 5000
  end_ckpt: 300000
  batch_size: 100

data:
  dataset: "ImageNet"
  image_size: 256
  channels: 3
  imagenet_default_mean_and_std: true
  num_workers: 8
  pin_mem: true

model:
  image_size: 256
  patch_size: 16
  mask_ratio: 0.75
  drop_path: 0.0
  normalize_target: true
  vit_depth: 24
  vit_heads: 16
  vit_dim: 1024
  vit_mlp_dim: 4096
  vit_num_classes: 1000
  decoder_width: 512
  decoder_depth: 8
  ema: false
  ema_rate: 0.999

optim:
  weight_decay: 0.05
  optimizer: "AdamW"
  lr: 0.00015
  lr_schedule: "cosine"  #linear, constant
  momentum: 0.9
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
  warmup_epochs: 40
  warmup_lr: 0.000001
  multiplier: 150 # lr / warmup_lr
  min_lr: 0.000001
  T_0: 100
  T_mul: 2

